name: Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Install Rust version
      run: rustup toolchain install 1.46.0
    - name: Select Rust version
      run: rustup default 1.46.0
    - name: Build
      run: cargo build
    - name: Run tests
      run: cargo test
    - name: Run Clippy
      run: cargo clippy
